### ISSUE TITLE
Ship setconf as ansible module

### ISSUE THREAD

**Issue by techtonik** [xyproto/setconf#15]
Ansible is a configuration management system. But funny enough, it lacks a good module for setting configuration.

`lineinfile` module https://docs.ansible.com/ansible/latest/modules/lineinfile_module.html doesn't detect if line is present in file unless you know [the hack with regexps](https://stackoverflow.com/questions/19390600/ansible-lineinfile-duplicates-line/21934455#21934455).

`blockinfile` module inserts extra markers and fails to insert newline before the blocks - https://github.com/ansible/ansible/issues/38417

And there is no native way to `setconf` values in configs.

**Comment by xyproto** [comment]
Thanks for reporting! I would like to add `setconf` as an Ansible module, but I'll have to read up on how to do it first, which may take time. If you know about anyone that would like to add it as an Ansible module, that would be most welcome too.

**Comment by techtonik** [comment]
The docs on how to do it are quite good https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_general.html
As for people who may support this I have to think about it. I guess it won't happen soon.

**Comment by xyproto** [comment]
Closing since it's been a while.
