### ISSUE TITLE
File truncated when no EOL at EOF

### ISSUE THREAD

**Issue by zappolowski** [xyproto/setconf#16]
Given the input file omits the trailing newline at the end of the file (encountered e.g. in `bin/grails` from [grails releases](https://github.com/grails/grails-core/releases)) the resulting line lacks the last line (which in the case of `grails` renders the script useless).

I was able to track it down to [this line](https://github.com/xyproto/setconf/blob/master/setconf.py#L284), which unconditionally removes the last element. A proposed fix is to just remove empty elements from the end like:
```patch
diff --git a/setconf.py b/setconf.py
index 3fadba9..9f42074 100755
--- a/setconf.py
+++ b/setconf.py
@@ -281,7 +281,11 @@ def changefile(filename, key, value, dummyrun=False, define=False, uncomment_fir
     try:
         with open(filename, 'rb') as f:
             data = f.read()
-            lines = data.split(NL)[:-1]
+            lines = data.split(NL)
+            for idx in range(len(lines) - 1, 0, -1):
+                if lines[idx] != b'':
+                    break
+                del lines[idx]
     except IOError:
         print("Can't read %s" % (filename))
         sysexit(2)
```

**Comment by xyproto** [comment]
Thanks for the pull request! I'll test this properly and then merge it.

**Comment by xyproto** [comment]
Tested and applied the patch. All tests pass. Sorry for the delay, and thanks for the patch!

**Comment by ntfc** [comment]
Hi @xyproto, apologies for bringing this up again, but would it be possible to create a `0.7.7` release with this fix? Thanks!

**Comment by xyproto** [comment]
Thanks for the reminder! I made a new release.

**Comment by ntfc** [comment]
Awesome, thank you! :D
