### ISSUE TITLE
Please note pkgsrc (NetBSD) in the Download section

### ISSUE THREAD

**Issue by krytarowski** [xyproto/setconf#3]
pkgsrc (NetBSD)

Binary package:

```
pkgin install py27-setconf
```

or install from sources:

```
cd /usr/pkgsrc/sysutils/py-setconf && make install
```

See also: http://pkgsrc.se/sysutils/py-setconf

**Comment by xyproto** [comment]
Updated the page. Thanks for making setconf available for NetBSD!
