### ISSUE TITLE
Increment values with spaces

### ISSUE THREAD

**Issue by AladW** [xyproto/setconf#6]
The man page says
> setconf my.conf x=1
> Sets x to 1 in my.conf, even if my.conf uses a different assignment,
> like x := 42, x : 42, x == 42, x :: 42 or x => 42.

My question is, how can I make this work with variable increments? For example, `setconf pkgver+=1 PKGBUILD` works, but `setconf .SRCINFO pkgver+=1` sets pkgver to 1, instead of incrementing it. Example .SRCINFO file:
```
pkgbase = ldm
	pkgdesc = A lightweight device mounter
	pkgver = 0.7
	pkgrel = 2
	url = https://github.com/LemonBoy/ldm
	install = ldm.install
	arch = i686
	arch = x86_64
	arch = armv7h
	license = MIT
	depends = udev
	depends = util-linux
	depends = glib2
	provides = ldm
	conflicts = ldm-git
	source = ldm-0.7.tar.gz::http://github.com/lemonboy/ldm/archive/v0.7.tar.gz
	sha256sums = fb464bffec5b7d0680009b43a95881e8c02ec07e84d6f7fb05206d666dc44bdb

pkgname = ldm
```
Using setconf from master a080bdc5c4da2def373a5e8197ee5cde95d50328

**Comment by xyproto** [comment]
Thanks for reporting! I will look into this.

**Comment by xyproto** [comment]
Fixed! Please test.

**Comment by AladW** [comment]
Works for me, thanks. :+1:
